### ISSUE TITLE
Any significant performance hit?

### ISSUE THREAD

**Issue by ncr** [eric1234/test_inline#1]
Even if there's big hit it's easy to define Kernel#Test as a noop:

```
def Kernel#Test; end
```

**Comment by eric1234** [comment]
The performance is mostly a non-issue.

I mention on my "Trade-offs" wiki page about defining Kernel#Test as a no-op although I suggest it for getting rid of Test::Inline as a run-time dependency if that bothers you.

From a performance standpoint Kernel#Test should only be in the execution path while the library/app is loading. Once it is running it will not even be calling Kernel#Test (unless it is reloading modules or something).

But even when it is in the execution path Kernel#Test checks if either:
1. Testing is setup (i.e. Test::Inline.setup has been called)
2. The current file is being executed

Only if one of those things are true does Kernel#Test even do anything. Otherwise it just returns. So while running the library app EVEN when in the execution path (which generally only happens on load) Kernel#Test is already almost a no-op.

**Comment by ncr** [comment]
Thanks for thorough answer. I'm really curious how this project develops over time.
